---
title: "simpleSVDtest"
output: html_document
date: "2024-02-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This markdown tests andgives examples for the vertical_corr function written in this library and the block SVD algorithm in general

```{r}
library(svdParallel)
library(devtools)
```

First a simple test:

```{r}
A <- matrix(c(3, -1, 1, 3, 1, 1, 4, -2,5,1), nrow = 5, ncol = 2, byrow = TRUE)
print(A)
```

```{r}
#This is generalized so I can use it for other datasets
n <- dim(A)[2] 
k <- floor(n/2) 

A <- scale(A)

A1 <- A[, 1:k]
A2 <- A[, (k+1):n]
```


```{r}
svd_A1 <- svd(A1)
svd_A2 <- svd(A2)

U_combined <- cbind(svd_A1$u %*% svd_A1$d, svd_A2$u %*% svd_A2$d)
svd_final <- svd(U_combined)
svd_final
```

```{r}
  U <- svd_final$u
  D <- svd_final$d
  V <- svd_final$v

  #formula for correlation from svd
  correlation_matrix <- V %*% diag(D^2) %*% t(V)
  correlation_matrix/correlation_matrix[1,1]
```

Next some examples using the native R datasets:

```{r}
# Load the datasets
data(mtcars)
data(iris)

# Ensure iris dataset is numeric only
iris <- iris[, sapply(iris, is.numeric)]

# Split the datasets into two partitions
partition1_mtcars <- mtcars[, 1:6]
partition2_mtcars <- mtcars[, 7:ncol(mtcars)]

partition1_iris <- iris[, 1:2]
partition2_iris <- iris[, 3:4]

# Run the vertical_corr function on the partitions
correlation_mtcars <- vertical_corr(scale(partition1_mtcars), scale(partition2_mtcars))
correlation_iris <- vertical_corr(scale(partition1_iris), scale(partition2_iris))

# Print out the results
print(correlation_mtcars)
print(correlation_iris)

```


```{r}
cor(iris)
cor(mtcars)
```


```{r}

```


```{r}

```
