package main

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"sync/atomic"
	"testing"
	"time"
)

// Explicit component measurement: real checked OT, GC, authenticated stores
// and two encrypted peers, with an independently computed routing oracle.
// This does not run LMM loss, DP, owner source access or a promotion release.
func TestGroupedRouteCapacityN2000C500(t *testing.T) {
	if os.Getenv("DSVERT_GROUPED_ROUTE_CAPACITY") != "1" {
		t.Skip("set DSVERT_GROUPED_ROUTE_CAPACITY=1 on the isolated proof host")
	}
	start := time.Now()
	s := groupedRouteTestSpec()
	s.Clusters, s.Slots, s.Predictors = 500, 4, 3
	s.NumericBound, s.Nonnegative = new(big.Int).Lsh(big.NewInt(1), 50), true
	rows, numeric, metadata, cols := 2000, 4, 6, 5
	labels, present := make([]int, rows), make([]bool, rows)
	live := make([]bool, rows)
	values := make([]Uint128, rows*numeric)
	publicMetadata := make([]Uint128, rows*metadata)
	for r := 0; r < rows; r++ {
		labels[r], present[r], live[r] = (r*137)%500, true, true
		for c := 0; c < numeric; c++ {
			values[r*numeric+c] = Uint128{Lo: uint64((r*103+c*17)%1025) << 40}
			p := uint64(1)
			if (c == 3 && r%113 == 0) || (c == 0 && r%157 == 0) {
				p, live[r] = 0, false
			}
			publicMetadata[r*metadata+c] = Uint128{Lo: p}
		}
		publicMetadata[r*metadata+numeric] = Uint128{Lo: uint64(labels[r])}
		publicMetadata[r*metadata+numeric+1] = Uint128{Lo: 1}
	}
	keys := [2][32]byte{crossGridStageTestKey(0), crossGridStageTestKey(1)}
	side, err := groupedRouteSeal(s, labels, present, keys[0])
	if err != nil {
		t.Fatal(err)
	}
	sources := [2][2]crossGridStageOutput{}
	for field, data := range [][]Uint128{values, publicMetadata} {
		for role := range sources {
			sources[role][field] = crossGridStageOutput{Share: make([]byte, 16*len(data)), Validity: make([]byte, len(data))}
		}
		for i, value := range data {
			// Public synthetic fixture shares only; every protocol mask/OT seed
			// remains generated by crypto/rand inside the real executor.
			hash := sha256.Sum256([]byte(fmt.Sprintf("synthetic routed capacity/%d/%d", field, i)))
			a := getUint128LE(hash[:16])
			putUint128LE(sources[0][field].Share[16*i:16*(i+1)], a)
			putUint128LE(sources[1][field].Share[16*i:16*(i+1)], value.Sub(a))
			sources[0][field].Validity[i], sources[1][field].Validity[i] = hash[16]&1, (hash[16]&1)^1
		}
	}
	base := exactGCTestSession(exactGCCircuitSpec{Operation: exactGCPrimitiveV, RingBits: 128, VectorLen: 1})
	plan := crossGridStageGraph{Version: "cross-grid-stage-graph-v1", Family: "lmm", Session: "synthetic-route-n2000-c500",
		Authorities: [2]string{base.GarblerID, base.EvaluatorID}, SchemaDigest: sha256.Sum256([]byte("synthetic C500 source schema")), SemanticKey: sha256.Sum256([]byte("synthetic C500 semantic release"))}
	for field, id := range []string{s.NumericStage, s.MetadataStage} {
		p := crossGridStagePlan{ID: id, Kind: "test.synthetic-source", Ring: 128, FPScale: 50,
			CoordOrder: make([]string, len(sources[0][field].Validity)), PublicBounds: map[string]int{"rows": rows}, SourceDigest: s.SourceDigest, ProfileDigest: s.ProfileDigest}
		if field == 1 {
			p.FPScale = 0
		}
		for i := range p.CoordOrder {
			p.CoordOrder[i] = fmt.Sprintf("source:%d", i)
		}
		plan.Stages = append(plan.Stages, p)
	}
	kernels := [2][]crossGridStageCompute{}
	for role := range kernels {
		for _, output := range sources[role] {
			output := output
			kernels[role] = append(kernels[role], func(io.ReadWriter, crossGridStageAttempt, []crossGridStageOutput) (crossGridStageOutput, error) {
				return output, nil
			})
		}
		var owner *groupedRouteSidecar
		if role == 0 {
			owner = side
		}
		graph, err := groupedRouteBuildStagedGraph(s, exactGCRole(role), owner, keys[role])
		if err != nil {
			t.Fatal(err)
		}
		kernels[role] = append(kernels[role], graph.Compute...)
		if role == 0 {
			plan.Stages = append(plan.Stages, graph.Plans...)
		}
	}
	dirs := [2]string{filepath.Join(t.TempDir(), "private"), filepath.Join(t.TempDir(), "private")}
	stores := [2]*crossGridStageStore{}
	for role := range stores {
		stores[role], err = crossGridStageOpenStore(dirs[role], keys[role], plan, exactGCRole(role))
		if err != nil {
			t.Fatal(err)
		}
		defer stores[role].Close()
	}
	left, right := net.Pipe()
	left.SetDeadline(start.Add(6 * time.Hour))
	right.SetDeadline(start.Add(6 * time.Hour))
	defer left.Close()
	defer right.Close()
	counts := [2]*primitiveVCountingRW{{Conn: left}, {Conn: right}}
	var attempted atomic.Int64
	var stopped atomic.Bool
	connections := [2]*coxBenchmarkConn{{counts[0], &attempted, &stopped, 256000000000}, {counts[1], &attempted, &stopped, 256000000000}}
	executors := [2]*crossGridStageExecutor{{Store: stores[0], Base: base}, {Store: stores[1], Base: base}}
	type result struct {
		out []crossGridStageOutput
		err error
	}
	ch := make(chan result, 1)
	go func() {
		out, e := executors[0].Execute(connections[0], kernels[0])
		left.Close()
		ch <- result{out, e}
	}()
	out, e := executors[1].Execute(connections[1], kernels[1])
	right.Close()
	results := [2]result{<-ch, {out, e}}
	measurement := map[string]any{"component": "authenticated-private-grouped-router", "n": rows, "clusters": s.Clusters, "slots": s.Slots, "predictors": s.Predictors,
		"seconds": time.Since(start).Seconds(), "garbler_bytes": counts[0].Written, "evaluator_bytes": counts[1].Written, "total_bytes": counts[0].Written + counts[1].Written,
		"traffic_limit_bytes": 256000000000, "time_limit_seconds": 21600, "budget_stop": stopped.Load(), "stages": len(plan.Stages),
		"completed": results[0].err == nil && results[1].err == nil, "oracle_equal": false, "production_release": false, "promoted": false,
		"transport": "two encrypted computation authorities via net.Pipe; synthetic authenticated source; proof host recorded by launcher"}
	defer func() {
		raw, _ := json.Marshal(measurement)
		t.Log(string(raw))
	}()
	if results[0].err != nil || results[1].err != nil {
		t.Fatalf("private C500 router did not complete: %v / %v", results[0].err, results[1].err)
	}
	a, b := results[0].out[len(plan.Stages)-1], results[1].out[len(plan.Stages)-1]
	// Independent stable scatter, never using the sidecar control generator.
	positions := make([]int, s.Clusters)
	for source, label := range labels {
		destination := label*s.Slots + positions[label]
		positions[label]++
		for c := 0; c < cols; c++ {
			want := Uint128{}
			if live[source] {
				if c == 0 {
					want.Lo = 1 << 50
				} else {
					want = values[source*numeric+c-1]
				}
			}
			i := destination*cols + c
			got := getUint128LE(a.Share[16*i : 16*(i+1)]).Add(getUint128LE(b.Share[16*i : 16*(i+1)]))
			if got != want || a.Validity[i]^b.Validity[i] != 1 {
				t.Fatalf("C500 private route oracle differs at public coordinate %d", i)
			}
		}
	}
	measurement["oracle_equal"] = true
}
