package main

// Dealer-free exact arithmetic for grouped kernels. No CLI/production dispatch.
// Security is the engine's two-authority semi-honest model with checked OT;
// the KOS check does not authenticate a malicious party's Beaver openings.
// Inputs MUST already be shares in Z/(2^192); widening narrower shares locally
// is not valid. The caller proves signed bounds and performs one secure final
// rescale. All operations here have zero modular arithmetic error.
import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"io"
	"math/bits"

	"github.com/markkurossi/mpc/ot"
	"github.com/markkurossi/mpc/p2p"
)

type groupedWord [3]uint64 // little-endian Ring192 transport words

func (a groupedWord) add(b groupedWord) (z groupedWord) {
	var carry uint64
	for i := range z {
		z[i], carry = bits.Add64(a[i], b[i], carry)
	}
	return
}
func (a groupedWord) sub(b groupedWord) (z groupedWord) {
	var carry uint64
	for i := range z {
		z[i], carry = bits.Sub64(a[i], b[i], carry)
	}
	return
}
func (a groupedWord) shl(n int) (z groupedWord) {
	for i := n / 64; i < 3; i++ {
		z[i] = a[i-n/64] << uint(n%64)
		if n%64 != 0 && i > n/64 {
			z[i] |= a[i-n/64-1] >> uint(64-n%64)
		}
	}
	return
}
func (a groupedWord) mul(b groupedWord) (z groupedWord) {
	for i := 0; i < 3; i++ {
		for j := 0; i+j < 3; j++ {
			hi, lo := bits.Mul64(a[i], b[j])
			var term groupedWord
			term[i+j] = lo
			if i+j+1 < 3 {
				term[i+j+1] = hi
			}
			z = z.add(term)
		}
	}
	return
}
func groupedRandomWord() (groupedWord, error) {
	var raw [24]byte
	if _, err := io.ReadFull(rand.Reader, raw[:]); err != nil {
		return groupedWord{}, err
	}
	return groupedDecodeWord(raw[:]), nil
}
func groupedDecodeWord(raw []byte) (z groupedWord) {
	for i := range z {
		z[i] = binary.LittleEndian.Uint64(raw[8*i:])
	}
	return
}
func groupedEncodeWords(words []groupedWord) []byte {
	raw := make([]byte, 24*len(words))
	for i, w := range words {
		for j, v := range w {
			binary.LittleEndian.PutUint64(raw[24*i+8*j:], v)
		}
	}
	return raw
}

// Two 128-bit checked OTs transport each 192-bit message, with identical
// choices. The high label has 64 unused zero bits. Neither mask nor triple
// is generated by a dealer; each sender subtracts its own fresh OT masks.
func groupedOTSend(conn *p2p.Conn, x []groupedWord) ([]groupedWord, error) {
	wires := make([]ot.Wire, len(x)*192*2)
	shares := make([]groupedWord, len(x))
	for i, value := range x {
		for bit := 0; bit < 192; bit++ {
			mask, err := groupedRandomWord()
			if err != nil {
				return nil, err
			}
			term := mask.add(value.shl(bit))
			k := (i*192 + bit) * 2
			wires[k] = ot.Wire{L0: ot.Label{D0: mask[0], D1: mask[1]}, L1: ot.Label{D0: term[0], D1: term[1]}}
			wires[k+1] = ot.Wire{L0: ot.Label{D0: mask[2]}, L1: ot.Label{D0: term[2]}}
			shares[i] = shares[i].sub(mask)
		}
	}
	transfer := ot.NewCOT(ot.NewCO(rand.Reader), rand.Reader, true, false)
	if err := transfer.InitSender(conn); err != nil {
		return nil, err
	}
	if err := transfer.Send(wires); err != nil {
		return nil, err
	}
	return shares, nil
}
func groupedOTReceive(conn *p2p.Conn, y []groupedWord) ([]groupedWord, error) {
	flags := make([]bool, len(y)*192*2)
	for i, w := range y {
		for bit := 0; bit < 192; bit++ {
			k := (i*192 + bit) * 2
			flags[k] = ((w[bit/64] >> uint(bit%64)) & 1) != 0
			flags[k+1] = flags[k]
		}
	}
	labels := make([]ot.Label, len(flags))
	transfer := ot.NewCOT(ot.NewCO(rand.Reader), rand.Reader, true, false)
	if err := transfer.InitReceiver(conn); err != nil {
		return nil, err
	}
	if err := transfer.Receive(flags, labels); err != nil {
		return nil, err
	}
	shares := make([]groupedWord, len(y))
	for i := range shares {
		for bit := 0; bit < 192; bit++ {
			k := (i*192 + bit) * 2
			if labels[k+1].D1 != 0 {
				return nil, fmt.Errorf("grouped arithmetic rejected")
			}
			shares[i] = shares[i].add(groupedWord{labels[k].D0, labels[k].D1, labels[k+1].D0})
		}
	}
	return shares, nil
}

type groupedArithmeticPlan struct {
	Contract [32]byte
	Previous [32]byte // authenticated preceding schedule receipt, zero for first
	Chunk    uint64
	Count    int
}

// Receipt is local, secret state: never return it or shares to the analyst.
// The integration owner must persist it atomically with output shares and
// consume each (session,chunk) once; this component has no durable store.
type groupedArithmeticResult struct {
	Shares  []groupedWord
	Receipt [32]byte
}

func groupedArithmeticSession(base exactGCSession, plan groupedArithmeticPlan) (exactGCSession, error) {
	if base.validate() != nil || plan.Contract == ([32]byte{}) || plan.Count < 1 || plan.Count > 1024 || (plan.Chunk == 0) != (plan.Previous == ([32]byte{})) {
		return exactGCSession{}, fmt.Errorf("grouped arithmetic rejected")
	}
	h := sha256.New()
	parent := exactGCContextDigest(base)
	h.Write(parent[:])
	h.Write(plan.Contract[:])
	h.Write(plan.Previous[:])
	var raw [16]byte
	binary.LittleEndian.PutUint64(raw[:8], plan.Chunk)
	binary.LittleEndian.PutUint64(raw[8:], uint64(plan.Count))
	h.Write(raw[:])
	base.Purpose = fmt.Sprintf("grouped-dealer-free-ring192-v1/%x", h.Sum(nil))
	base.Spec = exactGCCircuitSpec{Operation: exactGCPrimitiveV, RingBits: 192, VectorLen: 1}
	return base, base.validate()
}

// One registration point for Step 2; intentionally no generic remote method.
func registerGroupedExactArithmetic() func(io.ReadWriter, exactGCSession, exactGCRole, groupedArithmeticPlan, []groupedWord, []groupedWord) (*groupedArithmeticResult, error) {
	return groupedArithmeticProduct
}

func groupedArithmeticProduct(rw io.ReadWriter, base exactGCSession, role exactGCRole, plan groupedArithmeticPlan, x, y []groupedWord) (*groupedArithmeticResult, error) {
	s, err := groupedArithmeticSession(base, plan)
	if err != nil || len(x) != plan.Count || len(y) != plan.Count {
		return nil, fmt.Errorf("grouped arithmetic rejected")
	}
	secure, err := newExactGCSecureRecordRW(rw, s, role)
	if err != nil {
		return nil, fmt.Errorf("grouped arithmetic rejected")
	}
	conn := p2p.NewConn(secure)
	result, err := groupedArithmeticOnConn(conn, s, role, x, y)
	err = exactGCFinishConn(conn, rw, err)
	if err != nil {
		return nil, fmt.Errorf("grouped arithmetic rejected")
	}
	// Bind the local share bytes to the context and role using an independent MAC.
	context := exactGCContextDigest(s)
	mac := hmac.New(sha256.New, s.MasterKey[:])
	mac.Write([]byte("grouped-arithmetic-receipt-v1"))
	mac.Write(context[:])
	mac.Write([]byte{byte(role)})
	mac.Write(groupedEncodeWords(result))
	out := &groupedArithmeticResult{Shares: result}
	copy(out.Receipt[:], mac.Sum(nil))
	return out, nil
}

func groupedArithmeticOnConn(conn *p2p.Conn, s exactGCSession, role exactGCRole, x, y []groupedWord) ([]groupedWord, error) {
	begin, finish := exactGCHybridBeginGarbler, exactGCHybridFinishGarbler
	if role == exactGCRoleEvaluator {
		begin, finish = exactGCHybridBeginEvaluator, exactGCHybridFinishEvaluator
	}
	if err := begin(conn, s); err != nil {
		return nil, err
	}
	a, b := make([]groupedWord, len(x)), make([]groupedWord, len(x))
	for i := range a {
		var err error
		a[i], err = groupedRandomWord()
		if err != nil {
			return nil, err
		}
		b[i], err = groupedRandomWord()
		if err != nil {
			return nil, err
		}
	}
	var forward, reverse []groupedWord
	var err error
	if role == exactGCRoleGarbler {
		forward, err = groupedOTSend(conn, a)
		if err == nil {
			reverse, err = groupedOTReceive(conn, b)
		}
	} else {
		forward, err = groupedOTReceive(conn, b)
		if err == nil {
			reverse, err = groupedOTSend(conn, a)
		}
	}
	if err != nil {
		return nil, err
	}
	// c=(a0+a1)(b0+b1); neither authority knows the complete triple.
	c := make([]groupedWord, len(x))
	opening := make([]groupedWord, 2*len(x))
	for i := range x {
		c[i] = a[i].mul(b[i]).add(forward[i]).add(reverse[i])
		opening[i] = x[i].sub(a[i])
		opening[len(x)+i] = y[i].sub(b[i])
	}
	encoded := groupedEncodeWords(opening)
	var peer []byte
	if role == exactGCRoleGarbler {
		err = conn.SendData(encoded)
		if err == nil {
			err = conn.Flush()
		}
		if err == nil {
			peer, err = conn.ReceiveData()
		}
	} else {
		peer, err = conn.ReceiveData()
		if err == nil {
			err = conn.SendData(encoded)
		}
		if err == nil {
			err = conn.Flush()
		}
	}
	if err != nil || len(peer) != len(encoded) {
		return nil, fmt.Errorf("grouped arithmetic rejected")
	}
	z := make([]groupedWord, len(x))
	for i := range z {
		d := opening[i].add(groupedDecodeWord(peer[24*i:]))
		e := opening[len(x)+i].add(groupedDecodeWord(peer[24*(len(x)+i):]))
		z[i] = c[i].add(d.mul(b[i])).add(e.mul(a[i]))
		if role == exactGCRoleGarbler {
			z[i] = z[i].add(d.mul(e))
		}
	}
	if err := finish(conn, s); err != nil {
		return nil, err
	}
	return z, nil
}
