package main

import (
	"errors"
	"math/big"
)

// This profile is additive to the frozen f50/f100 source ABI. Only the complete
// shared predictor is rounded to q16. It is an exact integer specification of
// the Day-1 certified piecewise approximation, not an exact transcendental.
const (
	CoxGridCrossProfileID               = "cox-pwlinear64-exp-q16-q20-log-q20-v1"
	CoxGridCrossProfileSHA256           = "3ec6e885ddcf37c0471299b7b1745c80b18f8aa18dbec6ce56f865b1fda1c483"
	CoxGridCrossCertificateSHA256       = "27c6aa5a74f03c4ee2516e026fdaeaf3ce248d40451e8bbdb5c1ed421a542fe9"
	CoxGridCrossLn2Q20            int64 = 726817
	CoxGridCrossEventErrorQ24     int64 = 262144 // 2^24 / 64
	CoxGridCrossExpRelativeError        = 0.0144
	CoxGridCrossLogAbsoluteError        = 0.00006
	CoxGridCrossRiskMaxQ20        int64 = 31257610020000
)

// Generated by inst/cross-cox-v1/generate_numeric_cox_profile_v1.py using
// outward intervals and nearest-even knot rounding. The fixture and hashes
// pin every entry; the interpolation operation itself floors.
var CoxGridCrossExpKnotsQ20 = [65]uint32{
	352, 452, 580, 745, 956, 1228, 1576, 2024,
	2599, 3337, 4285, 5502, 7065, 9072, 11649, 14957,
	19205, 24660, 31664, 40658, 52206, 67033, 86072, 110519,
	141909, 182215, 233969, 300422, 385750, 495312, 635993, 816632,
	1048576, 1346398, 1728810, 2219835, 2850325, 3659890, 4699392, 6034138,
	7747987, 9948612, 12774271, 16402488, 21061212, 27043131, 34724068, 44586586,
	57250310, 73510853, 94389803, 121198907, 155622477, 199823216, 256578088, 329452786,
	423025751, 543175816, 697451553, 895545521, 1149903211, 1476504949, 1895869883, 2434345116,
	3125761002,
}

var CoxGridCrossLogKnotsQ20 = [65]int32{
	0, 16257, 32266, 48035, 63570, 78877, 93965, 108839,
	123504, 137968, 152234, 166309, 180198, 193905, 207435, 220793,
	233983, 247009, 259875, 272585, 285143, 297552, 309817, 321939,
	333923, 345771, 357487, 369074, 380534, 391870, 403085, 414181,
	425161, 436027, 446782, 457427, 467966, 478400, 488731, 498961,
	509092, 519126, 529065, 538911, 548665, 558330, 567906, 577395,
	586800, 596120, 605359, 614517, 623596, 632596, 641520, 650369,
	659144, 667846, 676476, 685036, 693527, 701949, 710304, 718593,
	726817,
}

// CoxGridCrossExpProfileQ16 evaluates exp(eta/2^16) at scale 2^20.
// Its only product has a 30-bit difference and 14-bit offset, below 2^44.
// The uint64 below holds that full product; both scalar operands are <=32 bits.
func CoxGridCrossExpProfileQ16(eta int32) (uint32, error) {
	if eta < -524288 || eta > 524288 {
		return 0, errors.New("cox profile input rejected")
	}
	if eta == 524288 {
		return CoxGridCrossExpKnotsQ20[64], nil
	}
	x := uint32(eta + 524288)
	index, offset := x>>14, x&16383
	base := CoxGridCrossExpKnotsQ20[index]
	difference := CoxGridCrossExpKnotsQ20[index+1] - base
	return base + uint32((uint64(difference)*uint64(offset))>>14), nil
}

// CoxGridCrossLogProfileQ20 evaluates log(risk/2^20), returning signed q20.
// Risk prefixes are exact wide sums, never scalar nonlinear operands. A
// secret leading-bit normalization puts the scalar operand in [1,2).
func CoxGridCrossLogProfileQ20(risk *big.Int) (int64, error) {
	if risk == nil || !risk.IsInt64() || risk.Int64() < 352 || risk.Int64() > CoxGridCrossRiskMaxQ20 {
		return 0, errors.New("cox profile input rejected")
	}
	exponent := risk.BitLen() - 21
	mantissa := new(big.Int).Set(risk)
	if exponent >= 0 {
		mantissa.Rsh(mantissa, uint(exponent))
	} else {
		mantissa.Lsh(mantissa, uint(-exponent))
	}
	x := uint32(mantissa.Uint64() - (1 << 20))
	index, offset := x>>14, x&16383
	base := CoxGridCrossLogKnotsQ20[index]
	difference := CoxGridCrossLogKnotsQ20[index+1] - base
	interpolant := int64(base) + ((int64(difference) * int64(offset)) >> 14)
	return interpolant + int64(exponent)*CoxGridCrossLn2Q20, nil
}
