package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"io"
	"math/big"
	"reflect"
	"strings"
	"testing"
	"time"

	"golang.org/x/crypto/chacha20"
	"golang.org/x/crypto/hkdf"
)

// sha256CounterReader is shared with the checked-in Python/IBM cross oracle.
// It is test-only; production randomness is HKDF-SHA256/ChaCha20.
type sha256CounterReader struct {
	seed    []byte
	counter uint64
	buffer  []byte
}

func (reader *sha256CounterReader) Read(output []byte) (int, error) {
	for len(reader.buffer) < len(output) {
		var counter [8]byte
		binary.BigEndian.PutUint64(counter[:], reader.counter)
		digest := sha256.Sum256(append(append([]byte(nil), reader.seed...), counter[:]...))
		reader.buffer = append(reader.buffer, digest[:]...)
		reader.counter++
	}
	copy(output, reader.buffer[:len(output)])
	reader.buffer = reader.buffer[len(output):]
	return len(output), nil
}

func TestExactDiscreteGaussianMatchesIBMPythonOracle(t *testing.T) {
	// Generated by testdata/discrete_gaussian_ibm_oracle.py, which directly
	// ports IBM's Apache-2.0 reference functions and uses the same deterministic
	// byte reader/uniform rejection contract as this test.
	vectors := []struct {
		sigmaSquared string
		want         []int64
	}{
		{"1/2", []int64{0, -1, -1, 1, 0, -1, 0, 0, -1, -1, 0, 0, 0, -1, 0, 1, 1, 1, 0, -1, -1, -1, 1, 0}},
		{"3/2", []int64{0, 0, -3, 1, 1, -1, 0, -2, 3, -2, 0, 1, 0, 0, 1, 0, -1, 0, 2, 1, -2, -1, 1, 0}},
		{"17/3", []int64{-1, 3, -1, 2, 2, 0, 0, -1, 1, -1, -2, 2, 3, -3, 0, -1, 1, -3, 0, -2, -1, -1, 1, -3}},
		{"560", []int64{18, -1, 73, 22, 16, -24, -6, -3, -32, -1, -10, 37, 0, 19, 27, -42, -14, -17, 23, 1, -15, -26, 12, -1}},
		{"1234567/89", []int64{-77, 40, 19, 107, -33, 96, 154, 131, 77, 109, 304, -131, 233, -56, -9, 44, -32, 329, 13, 82, -84, -55, 7, 241}},
	}
	for _, vector := range vectors {
		t.Run(strings.ReplaceAll(vector.sigmaSquared, "/", "_"), func(t *testing.T) {
			sigmaSquared := new(big.Rat)
			if _, ok := sigmaSquared.SetString(vector.sigmaSquared); !ok {
				t.Fatal("invalid test variance")
			}
			reader := &sha256CounterReader{seed: []byte(
				"dsVert/IBM-cross-oracle/v1/" + vector.sigmaSquared)}
			sampler := exactDGaussianSampler{random: reader}
			got := make([]int64, len(vector.want))
			for index := range got {
				value, err := sampler.discreteGaussian(sigmaSquared)
				if err != nil {
					t.Fatal(err)
				}
				if !value.IsInt64() {
					t.Fatal("oracle sample is outside int64")
				}
				got[index] = value.Int64()
			}
			if !reflect.DeepEqual(got, vector.want) {
				t.Fatalf("Go sampler differs from IBM/Python oracle:\n got %v\nwant %v", got, vector.want)
			}
		})
	}
}

func gaussianTestStreamBytes(
	t *testing.T, seed [32]byte, transcript [32]byte, info []byte, count int,
) []byte {
	t.Helper()
	derivation := hkdf.New(sha256.New, seed[:], transcript[:], info)
	material := make([]byte, chacha20.KeySize+chacha20.NonceSize)
	if _, err := io.ReadFull(derivation, material); err != nil {
		t.Fatal(err)
	}
	stream, err := chacha20.NewUnauthenticatedCipher(
		material[:chacha20.KeySize], material[chacha20.KeySize:])
	clear(material)
	if err != nil {
		t.Fatal(err)
	}
	result := make([]byte, count)
	stream.XORKeyStream(result, result)
	return result
}

func TestGaussianCoordinateStreamPreservesFirstSegmentAndRekeysUnbounded(t *testing.T) {
	if jointDPGaussianStreamSegmentBytes != 1<<38 {
		t.Fatal("production Gaussian stream does not preserve the complete legacy ChaCha20 domain")
	}
	seed := sha256.Sum256([]byte("segmented-coordinate-seed"))
	transcript := sha256.Sum256([]byte("segmented-coordinate-transcript"))
	info := []byte("dsVert/test/gaussian-coordinate-domain/v1")
	const segmentBytes = 64

	reader, err := jointDPGaussianNewCoordinateStream(
		seed, transcript, info, segmentBytes)
	if err != nil {
		t.Fatal(err)
	}
	defer reader.destroy()
	observed := make([]byte, 3*segmentBytes)
	if _, err := io.ReadFull(reader, observed[:17]); err != nil {
		t.Fatal(err)
	}
	if _, err := io.ReadFull(reader, observed[17:]); err != nil {
		t.Fatal(err)
	}
	expected := gaussianTestStreamBytes(
		t, seed, transcript, info, segmentBytes)
	for segment := 1; segment < 3; segment++ {
		segmentInfo := append(append([]byte(nil), info...), []byte(
			"/dsvert-chacha20-unbounded-stream-segment/v1/")...)
		segmentInfo = append(segmentInfo, []byte(big.NewInt(int64(segment)).String())...)
		expected = append(expected, gaussianTestStreamBytes(
			t, seed, transcript, segmentInfo, segmentBytes)...)
	}
	if !bytes.Equal(observed, expected) {
		t.Fatal("segmented Gaussian coordinate stream changed its domain contract")
	}

	reader.remaining = 0
	if _, ok := reader.nextSegment.SetString("18446744073709551616", 10); !ok {
		t.Fatal("invalid big.Int test segment")
	}
	one := make([]byte, 1)
	if _, err := io.ReadFull(reader, one); err != nil {
		t.Fatal(err)
	}
	if reader.nextSegment.String() != "18446744073709551617" {
		t.Fatal("Gaussian coordinate stream segment index wrapped")
	}
	reader.destroy()
	if _, err := reader.Read(one); err == nil {
		t.Fatal("destroyed Gaussian coordinate stream remained readable")
	}
}

func TestJointDPGaussianPlanExactCertificatesExhaustiveGrid(t *testing.T) {
	for _, epsilon := range []string{"0.1", "1", "8"} {
		for _, delta := range []string{"0.000001", "7.888609052210118e-31"} {
			for _, sensitivity := range []string{"1", "256.5"} {
				for _, coordinates := range []int{1, 1000, 1000000} {
					input := jointDPGaussianPlanInput{
						Epsilon: epsilon, Delta: delta,
						L2SensitivitySteps:   sensitivity,
						TotalCoordinateCount: coordinates,
					}
					plan, err := jointDPPlanVectorGaussian(input)
					if err != nil {
						t.Fatalf("%s/%s/%s/%d: %v", epsilon, delta, sensitivity, coordinates, err)
					}
					if !plan.CapabilityAvailable || plan.ExactRationalSampler ||
						!plan.FiniteSupportTransferCharged ||
						!plan.FixedWorkSampler ||
						plan.Mechanism != jointDPGaussianMechanism ||
						plan.ReleaseDeltaAggregation != "max_per_peer_not_sum" ||
						plan.NominalVarianceMultiplier != 2 ||
						plan.NominalStandardDeviationFactor !=
							"sqrt(2)_relative_to_one_full_draw" ||
						!plan.AtLeastOneHonestNoisePeer ||
						plan.MaximumColludingNoisePeers != 1 ||
						plan.AdversaryView == "" ||
						plan.AdversaryViewPrivacyArgument == "" ||
						plan.SourceShareHidingPrecondition == "" ||
						plan.SamplerBranchesOnProtectedValues ||
						plan.SamplerBranchesOnPrivateRandomness ||
						plan.SamplerFullScanSteps != plan.SamplerMagnitudeCount ||
						plan.SamplerCDFTableBytes != plan.SamplerMagnitudeCount*
							plan.SamplerRandomBytesPerCoordinate ||
						plan.HostConstantTimeClaim || !plan.TranscriptDPClaim ||
						!plan.LogicalTranscriptFixedShape ||
						plan.PhysicalTimingDPClaim {
						t.Fatalf("invalid capability certificate: %#v", plan)
					}
					if plan.RequestBindingSHA256 != jointDPGaussianRequestBinding(
						input, plan.EpsilonNumerator, plan.EpsilonDenominator,
						plan.AllocatedDeltaNumerator, plan.AllocatedDeltaDenominator,
						plan.L2SensitivityNumerator, plan.L2SensitivityDenominator) {
						t.Fatal("planner request binding changed")
					}
					parse := func(numerator, denominator string) *big.Rat {
						value := new(big.Rat)
						if _, ok := value.SetString(numerator + "/" + denominator); !ok {
							t.Fatalf("invalid rational %s/%s", numerator, denominator)
						}
						return value
					}
					eps := parse(plan.EpsilonNumerator, plan.EpsilonDenominator)
					allocated := parse(plan.AllocatedDeltaNumerator, plan.AllocatedDeltaDenominator)
					core := parse(plan.CoreDeltaNumerator, plan.CoreDeltaDenominator)
					implementation := parse(plan.PerPeerImplementationDeltaNum,
						plan.PerPeerImplementationDeltaDenom)
					rho := parse(plan.RhoNumerator, plan.RhoDenominator)
					exponent := parse(plan.ZCDPConversionExponentNumerator,
						plan.ZCDPConversionExponentDenom)
					sigmaSquared := parse(plan.SigmaSquaredNumerator,
						plan.SigmaSquaredDenominator)
					sens := parse(plan.L2SensitivityNumerator,
						plan.L2SensitivityDenominator)
					if new(big.Rat).Add(core, implementation).Cmp(allocated) > 0 {
						t.Fatal("delta split exceeds allocation")
					}
					logBound, ok := new(big.Int).SetString(plan.ZCDPLogUpperInteger, 10)
					if !ok || exponent.Cmp(new(big.Rat).SetInt(logBound)) < 0 || rho.Cmp(eps) > 0 {
						t.Fatal("zCDP conversion inequality is not certified")
					}
					wantSigma := new(big.Rat).Quo(
						new(big.Rat).Mul(sens, sens),
						new(big.Rat).Mul(big.NewRat(2, 1), rho))
					if sigmaSquared.Cmp(wantSigma) != 0 {
						t.Fatal("sigma squared calibration changed")
					}
					tailExponent := parse(plan.TailProofExponentNumerator,
						plan.TailProofExponentDenominator)
					tailTarget := parse(plan.TailProofTargetNumerator,
						plan.TailProofTargetDenominator)
					log2Target, err := jointDPGaussianCeilLog2(tailTarget)
					if err != nil || tailExponent.Cmp(new(big.Rat).SetFrac(
						new(big.Int).Mul(big.NewInt(7), log2Target), big.NewInt(10))) < 0 {
						t.Fatal("tail exponent does not prove the dyadic target")
					}
				}
			}
		}
	}
}

func TestJointDPGaussianAdversarialDecimalFailsQuickly(t *testing.T) {
	started := time.Now()
	_, err := jointDPPlanVectorGaussian(jointDPGaussianPlanInput{
		Epsilon: "1", Delta: "1e-10000", L2SensitivitySteps: "1",
		TotalCoordinateCount: 1000000,
	})
	if err == nil || time.Since(started) > 2*time.Second {
		t.Fatalf("extreme delta was not rejected cheaply: err=%v elapsed=%s", err, time.Since(started))
	}
	started = time.Now()
	_, err = jointDPPlanVectorGaussian(jointDPGaussianPlanInput{
		Epsilon: "1e10000", Delta: "1e-6", L2SensitivitySteps: "1",
		TotalCoordinateCount: 1,
	})
	if err == nil || time.Since(started) > 2*time.Second {
		t.Fatalf("extreme epsilon was not rejected cheaply: err=%v elapsed=%s", err, time.Since(started))
	}
}

func TestJointDPGaussianSymmetricProjectionDoesNotIncreaseTwoDrawMagnitude(t *testing.T) {
	for maximum := int64(0); maximum <= 16; maximum++ {
		bound := big.NewInt(maximum)
		for left := int64(-64); left <= 64; left++ {
			for right := int64(-64); right <= 64; right++ {
				projectedLeft := jointDPGaussianProject(big.NewInt(left), bound)
				projectedRight := jointDPGaussianProject(big.NewInt(right), bound)
				projectedMagnitude := new(big.Int).Abs(new(big.Int).Add(
					projectedLeft, projectedRight))
				originalMagnitude := new(big.Int).Abs(new(big.Int).Add(
					big.NewInt(left), big.NewInt(right)))
				if projectedMagnitude.Cmp(originalMagnitude) > 0 {
					t.Fatalf("M=%d x=%d y=%d: projected magnitude %s > %s",
						maximum, left, right, projectedMagnitude, originalMagnitude)
				}
			}
		}
	}
}

func jointDPGaussianTestInput(t testing.TB, peer string, seed [32]byte,
	source []*big.Int, upper []int64, shifts []int, chunkStart, total int,
) jointDPGaussianShareInput {
	t.Helper()
	transcript := sha256.Sum256([]byte("gaussian/transcript/" + t.Name()))
	context := jointDPCommitmentContext(
		transcript, jointDPGaussianCommitmentPurpose, peer)
	commitment := jointDPSeedCommitment(context, seed)
	release := sha256.Sum256([]byte("gaussian/release/" + t.Name()))
	encoded, err := exactGCEncodeWorkerCanonicalShares(source,
		exactGCCircuitSpec{Operation: jointDPVectorOperation,
			RingBits: 128, FracBits: 0, VectorLen: len(source)})
	if err != nil {
		t.Fatal(err)
	}
	upperText := make([]string, len(upper))
	for index, value := range upper {
		upperText[index] = big.NewInt(value).String()
	}
	return jointDPGaussianShareInput{
		Version: jointDPGaussianInputVersion, RingBits: 128, FracBits: 0,
		TotalCoordinateCount: total, ChunkStart: chunkStart,
		CoordinateCount: len(source), OutputLatticeBits: 8,
		Epsilon: "1", AllocatedDelta: "0.000001", L2SensitivitySteps: "1",
		ScaleShifts: append([]int(nil), shifts...), RawUpperBounds: upperText,
		ReleaseContractHash: hex.EncodeToString(release[:]),
		TranscriptHash:      hex.EncodeToString(transcript[:]), PeerName: peer,
		CommitmentContext: hex.EncodeToString(context[:]),
		SeedCommitment:    hex.EncodeToString(commitment[:]),
		PrivateSeed:       hex.EncodeToString(seed[:]), SourceShare: encoded,
	}
}

func TestJointDPGaussianStickyRechunkingAndMetadataDomainSeparation(t *testing.T) {
	seed := sha256.Sum256([]byte("gaussian-sticky-rechunk-seed"))
	full := jointDPGaussianTestInput(t, "peer-a", seed,
		[]*big.Int{big.NewInt(1), big.NewInt(2), big.NewInt(3), big.NewInt(4)},
		[]int64{20, 20, 20, 20}, []int{8, 8, 8, 8}, 0, 4)
	fullSpec, err := jointDPGaussianParseSpec(full)
	if err != nil {
		t.Fatal(err)
	}
	fullNoise, err := jointDPGaussianNoise(seed, fullSpec)
	if err != nil {
		t.Fatal(err)
	}
	defer exactGCZeroBigInts(fullNoise)
	part := jointDPGaussianTestInput(t, "peer-a", seed,
		[]*big.Int{big.NewInt(3), big.NewInt(4)}, []int64{20, 20},
		[]int{8, 8}, 2, 4)
	part.ReleaseContractHash, part.TranscriptHash = full.ReleaseContractHash, full.TranscriptHash
	transcript, _ := jointDPDecodeHex32(part.TranscriptHash, "transcript")
	context := jointDPCommitmentContext(
		transcript, jointDPGaussianCommitmentPurpose, "peer-a")
	part.CommitmentContext = hex.EncodeToString(context[:])
	partCommitment := jointDPSeedCommitment(context, seed)
	part.SeedCommitment = hex.EncodeToString(partCommitment[:])
	partSpec, err := jointDPGaussianParseSpec(part)
	if err != nil {
		t.Fatal(err)
	}
	partNoise, err := jointDPGaussianNoise(seed, partSpec)
	if err != nil {
		t.Fatal(err)
	}
	defer exactGCZeroBigInts(partNoise)
	if fullNoise[2].Cmp(partNoise[0]) != 0 || fullNoise[3].Cmp(partNoise[1]) != 0 {
		t.Fatal("public rechunking changed absolute-coordinate sticky noise")
	}

	streamBytes := func(spec jointDPGaussianSpec, local int) []byte {
		reader, err := jointDPGaussianCoordinateReader(seed, spec, local)
		if err != nil {
			t.Fatal(err)
		}
		result := make([]byte, 64)
		if _, err := io.ReadFull(reader, result); err != nil {
			t.Fatal(err)
		}
		return result
	}
	baseline := streamBytes(fullSpec, 0)
	changedShift := full
	changedShift.ScaleShifts = append([]int(nil), full.ScaleShifts...)
	changedShift.ScaleShifts[0] = 7
	changedShiftSpec, err := jointDPGaussianParseSpec(changedShift)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Equal(baseline, streamBytes(changedShiftSpec, 0)) {
		t.Fatal("scale-shift tamper reused a Gaussian coordinate stream")
	}
	changedBound := full
	changedBound.RawUpperBounds = append([]string(nil), full.RawUpperBounds...)
	changedBound.RawUpperBounds[0] = "21"
	changedBoundSpec, err := jointDPGaussianParseSpec(changedBound)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Equal(baseline, streamBytes(changedBoundSpec, 0)) {
		t.Fatal("bound tamper reused a Gaussian coordinate stream")
	}

	wrongPurpose := full
	wrongContext := jointDPCommitmentContext(transcript, "convolution", "peer-a")
	wrongPurpose.CommitmentContext = hex.EncodeToString(wrongContext[:])
	wrongCommitment := jointDPSeedCommitment(wrongContext, seed)
	wrongPurpose.SeedCommitment = hex.EncodeToString(wrongCommitment[:])
	if _, err := jointDPGaussianParseSpec(wrongPurpose); err == nil {
		t.Fatal("Laplace commitment purpose was accepted by Gaussian")
	}
}

func TestJointDPGaussianEndToEndTwoDrawsOnePublicClampNoOpenings(t *testing.T) {
	raw := []*big.Int{big.NewInt(0), big.NewInt(17), big.NewInt(20)}
	leftSource, rightSource := jointDPVectorConvolutionSplit(raw)
	leftSeed := sha256.Sum256([]byte("gaussian-left-seed"))
	rightSeed := sha256.Sum256([]byte("gaussian-right-seed"))
	shifts := []int{8, 0, 8}
	upper := []int64{10, 100, 20}
	leftInput := jointDPGaussianTestInput(
		t, "peer-a", leftSeed, leftSource, upper, shifts, 0, len(raw))
	rightInput := jointDPGaussianTestInput(
		t, "peer-b", rightSeed, rightSource, upper, shifts, 0, len(raw))
	rightInput.ReleaseContractHash = leftInput.ReleaseContractHash
	rightInput.TranscriptHash = leftInput.TranscriptHash
	transcript, _ := jointDPDecodeHex32(leftInput.TranscriptHash, "transcript")
	rightContext := jointDPCommitmentContext(
		transcript, jointDPGaussianCommitmentPurpose, "peer-b")
	rightCommitment := jointDPSeedCommitment(rightContext, rightSeed)
	rightInput.CommitmentContext = hex.EncodeToString(rightContext[:])
	rightInput.SeedCommitment = hex.EncodeToString(rightCommitment[:])
	leftSpec, err := jointDPGaussianParseSpec(leftInput)
	if err != nil {
		t.Fatal(err)
	}
	rightSpec, err := jointDPGaussianParseSpec(rightInput)
	if err != nil {
		t.Fatal(err)
	}
	leftNoise, err := jointDPGaussianNoise(leftSeed, leftSpec)
	if err != nil {
		t.Fatal(err)
	}
	defer exactGCZeroBigInts(leftNoise)
	rightNoise, err := jointDPGaussianNoise(rightSeed, rightSpec)
	if err != nil {
		t.Fatal(err)
	}
	defer exactGCZeroBigInts(rightNoise)
	left, err := jointDPGaussianSampleShare(leftInput)
	if err != nil {
		t.Fatal(err)
	}
	right, err := jointDPGaussianSampleShare(rightInput)
	if err != nil {
		t.Fatal(err)
	}
	if left.SourceValuesReturned || left.NoiseValuesReturned ||
		left.PrivateSeedReturned || left.PreclampValuesReturned ||
		left.TailProjectionApplied || !left.TailTruncationApplied ||
		!left.FixedWorkShapeVerified || !left.NoWrapHeadroomCertified {
		t.Fatal("Gaussian share exposed a protected intermediate or omitted its certificate")
	}
	finalized, err := jointDPGaussianFinalize(jointDPGaussianFinalizerInput{
		Version: jointDPGaussianFinalizerInputVersion, RingBits: 128, FracBits: 0,
		TotalCoordinateCount: len(raw), ChunkStart: 0, CoordinateCount: len(raw),
		OutputLatticeBits: 8, Epsilon: leftInput.Epsilon,
		AllocatedDelta:     leftInput.AllocatedDelta,
		L2SensitivitySteps: leftInput.L2SensitivitySteps,
		ScaleShifts:        shifts, RawUpperBounds: leftInput.RawUpperBounds,
		ReleaseContractHash: leftInput.ReleaseContractHash,
		TranscriptHash:      leftInput.TranscriptHash,
		LeftNoisedShare:     left.NoisedShare, RightNoisedShare: right.NoisedShare,
	})
	if err != nil {
		t.Fatal(err)
	}
	for index := range raw {
		want := new(big.Int).Lsh(new(big.Int).Set(raw[index]), uint(shifts[index]))
		want.Add(want, leftNoise[index])
		want.Add(want, rightNoise[index])
		bound := new(big.Int).Lsh(big.NewInt(upper[index]), uint(shifts[index]))
		if want.Sign() < 0 {
			want.SetInt64(0)
		} else if want.Cmp(bound) > 0 {
			want.Set(bound)
		}
		if finalized.ClampedScaledValues[index] != want.String() {
			t.Fatalf("coordinate %d=%s want=%s", index,
				finalized.ClampedScaledValues[index], want.String())
		}
	}
	if finalized.PreclampValuesReturned || !finalized.NoWrapHeadroomCertified {
		t.Fatal("Gaussian finalizer exposed preclamp values or omitted no-wrap proof")
	}
	decoded, err := base64.StdEncoding.DecodeString(left.NoisedShare)
	if err != nil || len(decoded) != 16*len(raw) {
		t.Fatal("Gaussian noised share is not canonical Ring128")
	}
}

func jointDPGaussianTestGenericHockeyStick(
	left, right map[int]*big.Rat, expEpsilon *big.Rat,
) *big.Rat {
	keys := make(map[int]struct{}, len(left)+len(right))
	for value := range left {
		keys[value] = struct{}{}
	}
	for value := range right {
		keys[value] = struct{}{}
	}
	result := new(big.Rat)
	for value := range keys {
		leftMass := left[value]
		if leftMass == nil {
			leftMass = new(big.Rat)
		}
		rightMass := right[value]
		if rightMass == nil {
			rightMass = new(big.Rat)
		}
		difference := new(big.Rat).Sub(leftMass,
			new(big.Rat).Mul(expEpsilon, rightMass))
		if difference.Sign() > 0 {
			result.Add(result, difference)
		}
	}
	return result
}

func jointDPGaussianTestTranslatePMF(
	pmf map[int]*big.Rat, offset int,
) map[int]*big.Rat {
	result := make(map[int]*big.Rat, len(pmf))
	for value, mass := range pmf {
		result[value+offset] = new(big.Rat).Set(mass)
	}
	return result
}

func TestJointDPGaussianKnownPeerViewIsOnlyFixedPostProcessing(t *testing.T) {
	// This distribution-independent oracle locks the key conditional-view
	// step: after fixing the corrupt peer's share, seed and complete draw, its
	// contribution is a translation. Translation preserves both directed
	// hockey-stick divergences of the remaining honest full mechanism.
	honestLeft := map[int]*big.Rat{
		-1: big.NewRat(1, 4), 0: big.NewRat(1, 2), 1: big.NewRat(1, 4),
	}
	honestRight := map[int]*big.Rat{
		0: big.NewRat(1, 4), 1: big.NewRat(1, 2), 2: big.NewRat(1, 4),
	}
	expEpsilon := big.NewRat(3, 2)
	forward := jointDPGaussianTestGenericHockeyStick(
		honestLeft, honestRight, expEpsilon)
	reverse := jointDPGaussianTestGenericHockeyStick(
		honestRight, honestLeft, expEpsilon)
	for corruptKnownContribution := -16; corruptKnownContribution <= 16; corruptKnownContribution++ {
		translatedLeft := jointDPGaussianTestTranslatePMF(
			honestLeft, corruptKnownContribution)
		translatedRight := jointDPGaussianTestTranslatePMF(
			honestRight, corruptKnownContribution)
		if jointDPGaussianTestGenericHockeyStick(
			translatedLeft, translatedRight, expEpsilon).Cmp(forward) != 0 ||
			jointDPGaussianTestGenericHockeyStick(
				translatedRight, translatedLeft, expEpsilon).Cmp(reverse) != 0 {
			t.Fatal("conditioning on one peer's known draw changed privacy divergence")
		}
	}
	plan, err := jointDPPlanVectorGaussian(jointDPGaussianPlanInput{
		Epsilon: "1", Delta: "0.000001", L2SensitivitySteps: "1",
		TotalCoordinateCount: 8,
	})
	if err != nil || !plan.AtLeastOneHonestNoisePeer ||
		plan.MaximumColludingNoisePeers != 1 ||
		plan.ReleaseDeltaAggregation != "max_per_peer_not_sum" ||
		plan.SourceShareHidingPrecondition == "" {
		t.Fatalf("conditional adversary-view certificate missing: %#v %v", plan, err)
	}
}

func benchmarkJointDPGaussianFixedNoise(b *testing.B, coordinates int) {
	seed := sha256.Sum256([]byte("gaussian-scalable-fallback-benchmark"))
	source := make([]*big.Int, coordinates)
	upper := make([]int64, coordinates)
	shifts := make([]int, coordinates)
	for index := range source {
		source[index] = new(big.Int)
		upper[index] = 1_000_000
	}
	input := jointDPGaussianTestInput(
		b, "peer-a", seed, source, upper, shifts, 0, coordinates)
	spec, err := jointDPGaussianParseSpec(input)
	if err != nil {
		b.Fatal(err)
	}
	b.ResetTimer()
	for iteration := 0; iteration < b.N; iteration++ {
		noise, noiseErr := jointDPGaussianNoise(seed, spec)
		if noiseErr != nil {
			b.Fatal(noiseErr)
		}
		exactGCZeroBigInts(noise)
	}
	b.StopTimer()
	b.ReportMetric(0, "secure-cdf-gates")
	b.ReportMetric(float64(coordinates), "coordinates")
}

func BenchmarkJointDPGaussianScalableFallbackP1(b *testing.B) {
	benchmarkJointDPGaussianFixedNoise(b, 1)
}

func BenchmarkJointDPGaussianScalableFallbackP2(b *testing.B) {
	benchmarkJointDPGaussianFixedNoise(b, 2)
}

func BenchmarkJointDPGaussianScalableFallbackP8(b *testing.B) {
	benchmarkJointDPGaussianFixedNoise(b, 8)
}

func BenchmarkJointDPGaussianScalableFallbackP64(b *testing.B) {
	benchmarkJointDPGaussianFixedNoise(b, 64)
}

func BenchmarkJointDPGaussianAdversarialPlanRejection(b *testing.B) {
	for index := 0; index < b.N; index++ {
		_, _ = jointDPPlanVectorGaussian(jointDPGaussianPlanInput{
			Epsilon: "1", Delta: "1e-10000", L2SensitivitySteps: "1",
			TotalCoordinateCount: 1000000,
		})
	}
}
