// k2_beaver_google.go: Beaver protocol — 1:1 port of Google C++ beaver_triple_utils.cc
//
// All operations use explicit modulus (Ring63) matching the C++ exactly.
// Functions mirror the C++ names for traceability.

package main

import "math/big"

// BeaverTripleVec holds element-wise Beaver triple shares for one party.
// C = A*B (mod modulus) — generated by trusted dealer.
type BeaverTripleVec struct {
	A []uint64
	B []uint64
	C []uint64
}

// SampleBeaverTripleVector generates correlated Beaver triples.
// Port of C++ SampleBeaverVectorShareWithPrng.
func SampleBeaverTripleVector(length int, r Ring63) (party0, party1 BeaverTripleVec) {
	party0 = BeaverTripleVec{
		A: make([]uint64, length),
		B: make([]uint64, length),
		C: make([]uint64, length),
	}
	party1 = BeaverTripleVec{
		A: make([]uint64, length),
		B: make([]uint64, length),
		C: make([]uint64, length),
	}

	for i := 0; i < length; i++ {
		a := cryptoRandUint64K2() % r.Modulus
		b := cryptoRandUint64K2() % r.Modulus
		// C = A * B mod modulus (ring multiplication, matching C++ ModMul)
		c := modMulBig63(a, b, r.Modulus)

		// Split into shares
		party0.A[i], party1.A[i] = r.SplitShare(a)
		party0.B[i], party1.B[i] = r.SplitShare(b)
		party0.C[i], party1.C[i] = r.SplitShare(c)
	}
	return
}

// BatchedMultState holds a party's state after round 1 of Beaver multiplication.
type BatchedMultState struct {
	ShareXMinusA []uint64
	ShareYMinusB []uint64
}

// MultGateMessage holds the message sent between parties in Beaver multiplication.
type MultGateMessage struct {
	XMinusAShares []uint64
	YMinusBShares []uint64
}

// GenerateBatchedMultiplicationGateMessage computes round 1 of Beaver protocol.
// Port of C++ GenerateBatchedMultiplicationGateMessage.
func GenerateBatchedMultiplicationGateMessage(
	shareX, shareY []uint64,
	beaver BeaverTripleVec,
	r Ring63,
) (state BatchedMultState, msg MultGateMessage) {
	n := len(shareX)
	state.ShareXMinusA = make([]uint64, n)
	state.ShareYMinusB = make([]uint64, n)
	msg.XMinusAShares = make([]uint64, n)
	msg.YMinusBShares = make([]uint64, n)

	for i := 0; i < n; i++ {
		state.ShareXMinusA[i] = r.Sub(shareX[i], beaver.A[i])
		state.ShareYMinusB[i] = r.Sub(shareY[i], beaver.B[i])
	}
	copy(msg.XMinusAShares, state.ShareXMinusA)
	copy(msg.YMinusBShares, state.ShareYMinusB)
	return
}

// GenerateBatchedMultiplicationOutputPartyZero computes P0's output.
// Port of C++ GenerateBatchedMultiplicationOutputPartyZero.
// Output: [XY]_0 = [C]_0 + [B]_0*(X-A) + [A]_0*(Y-B) + (X-A)*(Y-B)
func GenerateBatchedMultiplicationOutputPartyZero(
	state BatchedMultState,
	beaver BeaverTripleVec,
	otherMsg MultGateMessage,
	r Ring63,
) []uint64 {
	n := len(state.ShareXMinusA)
	result := make([]uint64, n)

	for i := 0; i < n; i++ {
		// Reconstruct (X-A) and (Y-B)
		xMinusA := r.Add(state.ShareXMinusA[i], otherMsg.XMinusAShares[i])
		yMinusB := r.Add(state.ShareYMinusB[i], otherMsg.YMinusBShares[i])

		// [B]_0 * (X-A)
		bTimesXA := modMulBig63(beaver.B[i], xMinusA, r.Modulus)
		// [A]_0 * (Y-B)
		aTimesYB := modMulBig63(beaver.A[i], yMinusB, r.Modulus)
		// (X-A) * (Y-B) — only Party Zero
		xaTimesYB := modMulBig63(xMinusA, yMinusB, r.Modulus)

		// [XY]_0 = [C]_0 + [B]_0*(X-A) + [A]_0*(Y-B) + (X-A)*(Y-B)
		result[i] = r.Add(r.Add(r.Add(beaver.C[i], bTimesXA), aTimesYB), xaTimesYB)
	}
	return result
}

// GenerateBatchedMultiplicationOutputPartyOne computes P1's output.
// Port of C++ GenerateBatchedMultiplicationOutputPartyOne.
// Output: [XY]_1 = [C]_1 + [B]_1*(X-A) + [A]_1*(Y-B)
func GenerateBatchedMultiplicationOutputPartyOne(
	state BatchedMultState,
	beaver BeaverTripleVec,
	otherMsg MultGateMessage,
	r Ring63,
) []uint64 {
	n := len(state.ShareXMinusA)
	result := make([]uint64, n)

	for i := 0; i < n; i++ {
		xMinusA := r.Add(state.ShareXMinusA[i], otherMsg.XMinusAShares[i])
		yMinusB := r.Add(state.ShareYMinusB[i], otherMsg.YMinusBShares[i])

		bTimesXA := modMulBig63(beaver.B[i], xMinusA, r.Modulus)
		aTimesYB := modMulBig63(beaver.A[i], yMinusB, r.Modulus)

		// [XY]_1 = [C]_1 + [B]_1*(X-A) + [A]_1*(Y-B) — NO (X-A)*(Y-B) for P1
		result[i] = r.Add(r.Add(beaver.C[i], bTimesXA), aTimesYB)
	}
	return result
}

// TruncateSharePartyZero truncates P0's share by divisor.
// Port of C++ TruncateSharePartyZero.
// result[i] = share[i] / divisor (integer division in the ring)
func TruncateSharePartyZero(shares []uint64, divisor uint64, modulus uint64) []uint64 {
	result := make([]uint64, len(shares))
	for i, s := range shares {
		result[i] = (s / divisor) % modulus
	}
	return result
}

// TruncateSharePartyOne truncates P1's share by divisor.
// Port of C++ TruncateSharePartyOne.
// result[i] = modulus - ((modulus - share[i]) / divisor) mod modulus
func TruncateSharePartyOne(shares []uint64, divisor uint64, modulus uint64) []uint64 {
	result := make([]uint64, len(shares))
	for i, s := range shares {
		if s == 0 {
			result[i] = 0
		} else {
			negS := (modulus - s) % modulus
			result[i] = (modulus - (negS / divisor)) % modulus
		}
	}
	return result
}

// HadamardProductPartyZero computes the full Hadamard product with truncation for P0.
// Port of C++ HadamardProductPartyZero.
func HadamardProductPartyZero(
	state BatchedMultState,
	beaver BeaverTripleVec,
	otherMsg MultGateMessage,
	fracBits int,
	r Ring63,
) []uint64 {
	raw := GenerateBatchedMultiplicationOutputPartyZero(state, beaver, otherMsg, r)
	return TruncateSharePartyZero(raw, uint64(1)<<fracBits, r.Modulus)
}

// HadamardProductPartyOne computes the full Hadamard product with truncation for P1.
func HadamardProductPartyOne(
	state BatchedMultState,
	beaver BeaverTripleVec,
	otherMsg MultGateMessage,
	fracBits int,
	r Ring63,
) []uint64 {
	raw := GenerateBatchedMultiplicationOutputPartyOne(state, beaver, otherMsg, r)
	return TruncateSharePartyOne(raw, uint64(1)<<fracBits, r.Modulus)
}

// --- Convenience: full Hadamard product simulated locally ---

// HadamardProductLocal computes element-wise x*y on shares with truncation.
// Simulates both parties.
func HadamardProductLocal(
	x0, y0, x1, y1 []uint64,
	fracBits int,
	r Ring63,
) (res0, res1 []uint64) {
	n := len(x0)
	beaver0, beaver1 := SampleBeaverTripleVector(n, r)

	state0, msg0 := GenerateBatchedMultiplicationGateMessage(x0, y0, beaver0, r)
	state1, msg1 := GenerateBatchedMultiplicationGateMessage(x1, y1, beaver1, r)

	res0 = HadamardProductPartyZero(state0, beaver0, msg1, fracBits, r)
	res1 = HadamardProductPartyOne(state1, beaver1, msg0, fracBits, r)
	return
}

// --- ScalarVectorProduct ---
// Port of C++ scalar_vector_product.cc

// ScalarVectorProductPartyZero multiplies public scalar by P0's share vector.
// P0: floor((a * b_0 - a * modulus) / 2^lf) % modulus
func ScalarVectorProductPartyZero(scalarA float64, vectorB []uint64, r Ring63) []uint64 {
	negative := scalarA < 0
	if negative {
		scalarA = -scalarA
	}

	ringA := r.FromDouble(scalarA)
	result := make([]uint64, len(vectorB))

	aBig := new(big.Int).SetUint64(ringA)
	modBig := new(big.Int).SetUint64(r.Modulus)
	aTimesMod := new(big.Int).Mul(aBig, modBig) // a * modulus (128-bit)
	fracShift := new(big.Int).SetUint64(uint64(1) << r.FracBits)

	for i, b := range vectorB {
		// Guard: when b==0, any scalar * 0 = 0 in Ring63.
		// The standard formula (ab - a*mod) produces garbage when b=0
		// because it assumes the share pair wraps around the modulus.
		// This occurs when eta shares are literal zeros (e.g., beta=0 at iter 1).
		if b == 0 {
			result[i] = 0
			continue
		}
		// a * b_0
		ab := new(big.Int).Mul(aBig, new(big.Int).SetUint64(b))
		// a * b_0 - a * modulus
		ab.Sub(ab, aTimesMod)
		// >> fracBits (arithmetic shift, since value is negative)
		ab.Div(ab, fracShift) // Div truncates toward zero for big.Int
		// % modulus
		ab.Mod(ab, modBig)
		result[i] = ab.Uint64()
	}

	if negative {
		for i := range result {
			result[i] = r.Neg(result[i])
		}
	}

	return result
}

// ScalarVectorProductPartyOne multiplies public scalar by P1's share vector.
// P1: floor((a * b_1) / 2^lf) % modulus
func ScalarVectorProductPartyOne(scalarA float64, vectorB []uint64, r Ring63) []uint64 {
	negative := scalarA < 0
	if negative {
		scalarA = -scalarA
	}

	ringA := r.FromDouble(scalarA)
	result := make([]uint64, len(vectorB))

	for i, b := range vectorB {
		// TruncMul: (a * b) >> fracBits % modulus
		result[i] = r.TruncMul(ringA, b)
	}

	if negative {
		for i := range result {
			result[i] = r.Neg(result[i])
		}
	}

	return result
}

// ============================================================================
// Command: k2-gen-beaver-triples
// Generates Beaver triples ENTIRELY in the FixedPoint ring (no float64).
// Returns base64 FP shares for both parties.
// ============================================================================

type K2GenBeaverTriplesInput struct {
	N        int `json:"n"`         // number of triples
	FracBits int `json:"frac_bits"` // fractional bits
}

type K2GenBeaverTriplesOutput struct {
	Party0U string `json:"party0_u"` // base64 FP
	Party0V string `json:"party0_v"`
	Party0W string `json:"party0_w"`
	Party1U string `json:"party1_u"`
	Party1V string `json:"party1_v"`
	Party1W string `json:"party1_w"`
}

func handleK2GenBeaverTriples() {
	var input K2GenBeaverTriplesInput
	mpcReadInput(&input)
	if input.FracBits <= 0 {
		input.FracBits = 20
	}

	n := input.N
	r := NewRing63(input.FracBits)

	// Generate Beaver triples entirely in Ring63 (uint64 mod 2^63),
	// matching the validated Google C++ port.
	// C = A * B mod modulus (ring multiplication via modMulBig63).
	p0, p1 := SampleBeaverTripleVector(n, r)

	// Convert Ring63 uint64 shares to FP (int64) for base64 transport.
	// ring63ToFP correctly handles the signed interpretation.
	mpcWriteOutput(K2GenBeaverTriplesOutput{
		Party0U: bytesToBase64(fpVecToBytes(ring63ToFP(p0.A))),
		Party0V: bytesToBase64(fpVecToBytes(ring63ToFP(p0.B))),
		Party0W: bytesToBase64(fpVecToBytes(ring63ToFP(p0.C))),
		Party1U: bytesToBase64(fpVecToBytes(ring63ToFP(p1.A))),
		Party1V: bytesToBase64(fpVecToBytes(ring63ToFP(p1.B))),
		Party1W: bytesToBase64(fpVecToBytes(ring63ToFP(p1.C))),
	})
}

// ============================================================================
// Command: k2-beaver-matvec-round1
// Round 1 of Beaver matrix-vector multiply: X^T * r.
// Each party computes [X-A] and [r-B] to send to peer.
// ============================================================================

type K2BeaverMatvecR1Input struct {
	XShare    []float64 `json:"x_share"`     // n*p (row-major) — this party's share of X
	RShare    []float64 `json:"r_share"`     // n — this party's share of r
	AShare    []float64 `json:"a_share"`     // n*p — Beaver triple A share
	BShare    []float64 `json:"b_share"`     // n — Beaver triple B share
	N         int       `json:"n"`
	P         int       `json:"p"`
	FracBits  int       `json:"frac_bits"`
}

type K2BeaverMatvecR1Output struct {
	XMinusA []float64 `json:"x_minus_a"` // n*p
	RMinusB []float64 `json:"r_minus_b"` // n
}

func handleK2BeaverMatvecR1() {
	var input K2BeaverMatvecR1Input
	mpcReadInput(&input)

	n := input.N
	p := input.P
	xMinusA := make([]float64, n*p)
	rMinusB := make([]float64, n)

	for i := range xMinusA {
		xMinusA[i] = input.XShare[i] - input.AShare[i]
	}
	for i := range rMinusB {
		rMinusB[i] = input.RShare[i] - input.BShare[i]
	}

	mpcWriteOutput(K2BeaverMatvecR1Output{XMinusA: xMinusA, RMinusB: rMinusB})
}

// ============================================================================
// Command: k2-beaver-matvec-round2
// Round 2: compute this party's share of Z = X^T * r.
// Uses the Beaver formula with truncation.
// ============================================================================

type K2BeaverMatvecR2Input struct {
	// Own round-1 message
	OwnXMinusA []float64 `json:"own_x_minus_a"` // n*p
	OwnRMinusB []float64 `json:"own_r_minus_b"` // n
	// Peer's round-1 message
	PeerXMinusA []float64 `json:"peer_x_minus_a"` // n*p
	PeerRMinusB []float64 `json:"peer_r_minus_b"` // n
	// Beaver triple shares
	AShare []float64 `json:"a_share"` // n*p
	BShare []float64 `json:"b_share"` // n
	CShare []float64 `json:"c_share"` // p (C = sum_i A[i,:] * B[i])
	// Protocol
	N       int `json:"n"`
	P       int `json:"p"`
	PartyID int `json:"party_id"` // 0 or 1
}

type K2BeaverMatvecR2Output struct {
	GradientShare []float64 `json:"gradient_share"` // p scalars
}

func handleK2BeaverMatvecR2() {
	var input K2BeaverMatvecR2Input
	mpcReadInput(&input)

	n := input.N
	p := input.P

	// Reconstruct full (X-A) and (r-B)
	fullXMinusA := make([]float64, n*p)
	fullRMinusB := make([]float64, n)
	for i := range fullXMinusA {
		fullXMinusA[i] = input.OwnXMinusA[i] + input.PeerXMinusA[i]
	}
	for i := range fullRMinusB {
		fullRMinusB[i] = input.OwnRMinusB[i] + input.PeerRMinusB[i]
	}

	// Z_i = C_i + A_i^T * (r-B) + (X-A)^T * B_i + [party0] * (X-A)^T * (r-B)
	gradient := make([]float64, p)

	// Start with C share
	copy(gradient, input.CShare)

	// A_i^T * (r-B): for each feature j, sum_i A[i,j] * (r-B)[i]
	for j := 0; j < p; j++ {
		for i := 0; i < n; i++ {
			gradient[j] += input.AShare[i*p+j] * fullRMinusB[i]
		}
	}

	// (X-A)^T * B_i: for each feature j, sum_i (X-A)[i,j] * B[i]
	for j := 0; j < p; j++ {
		for i := 0; i < n; i++ {
			gradient[j] += fullXMinusA[i*p+j] * input.BShare[i]
		}
	}

	// Party 0 only: (X-A)^T * (r-B)
	if input.PartyID == 0 {
		for j := 0; j < p; j++ {
			for i := 0; i < n; i++ {
				gradient[j] += fullXMinusA[i*p+j] * fullRMinusB[i]
			}
		}
	}

	mpcWriteOutput(K2BeaverMatvecR2Output{GradientShare: gradient})
}
