args <- commandArgs(TRUE)
root <- normalizePath(args[[1]])
out <- normalizePath(args[[2]])
pkgload::load_all(file.path(root, "dsVert"), quiet = TRUE)
pkgload::load_all(file.path(root, "dsVertClient"), quiet = TRUE)
Sys.setenv(NOT_CRAN = "true")
env <- new.env(parent = asNamespace("dsVertClient"))
for (path in list.files(file.path(root, "dsVertClient/tests/testthat"), pattern = "^helper.*\\.R$", full.names = TRUE)) sys.source(path, env)
result <- testthat::test_file(file.path(root, "dsVertClient/tests/testthat/test-dsi-text-frame.R"), env = env, reporter = "summary")
frame <- as.data.frame(result)
write.csv(frame[setdiff(names(frame), "result")], file.path(out, "client-test-dsi-text-frame.R.csv"), row.names = FALSE)
stopifnot(all(frame$failed == 0), all(!frame$error), all(frame$warning == 0), all(frame$skipped == 0))
