// distributed_comparison.go: Distributed secure comparison protocol.
//
// Implements [x < threshold] where x = x0 + x1 (secret-shared) and threshold
// is public, using DCF (Distributed Comparison Function).
//
// Protocol (2 rounds):
//   Preprocessing (dealer): Generate DCF keys + random masks
//   Round 1: Each party computes masked_eta = eta_share + mask, sends to peer
//   Round 2: Each party reconstructs full masked value, evaluates DCF
//
// The dealer generates preprocessing. In DataSHIELD, one SERVER is the dealer
// (not the client) so the client never learns the random mask.
//
// This file uses the DCF primitives from k2_dcf.go (already in mhe-tool).
// For the k2-mpc-tool module, we duplicate the DCF code minimally.
// In production, both modules share the same DCF implementation.

package main

// No additional imports needed — uses DCF from dcf.go and cryptoRandUint64 from util.go

// --- Comparison preprocessing (generated by dealer) ---

// CmpPreprocessParty holds one party's preprocessing for a batch of comparisons.
type CmpPreprocessParty struct {
	Keys      []DCFKeyCompact // DCF keys (one per comparison per element)
	MaskShare []uint64        // party's share of random mask (one per element)
	NumBits   int             // domain bits for DCF evaluation
}

// DCFKeyCompact is a serializable DCF key (same as DCFKey from mhe-tool).
// We duplicate the struct here to keep k2-mpc-tool self-contained.
type DCFKeyCompact = DCFKey

// CmpPreprocessBatch generates preprocessing for nCmp comparisons on n elements.
//
// For Ring63 values: eta is signed (values >= Modulus/2 are negative).
// We shift to unsigned by adding SignThreshold to both value and threshold:
//   [x < threshold] ≡ [(x + offset) < (threshold + offset)] mod Modulus
// where offset = SignThreshold = 2^62. This puts standardized data (~[-10,10])
// into the range [2^62 - 10M, 2^62 + 10M], avoiding wraparound.
//
// DCF domain: numBits = NumRingBits (63). Mask range is limited to prevent overflow.
func CmpPreprocessBatch(rp RingParams, n int, thresholds []uint64) ([]CmpPreprocessParty, []CmpPreprocessParty) {
	nCmp := len(thresholds)
	numBits := rp.NumRingBits // 63
	mod := rp.Modulus         // 2^63

	// Max meaningful value in standardized data: ~20 * 2^fracBits
	// Safe mask range: [0, mod/4) — leaves room for value + mask < mod
	safeMax := mod / 4

	p0 := make([]CmpPreprocessParty, nCmp)
	p1 := make([]CmpPreprocessParty, nCmp)

	for j := 0; j < nCmp; j++ {
		p0[j].NumBits = numBits
		p1[j].NumBits = numBits
		p0[j].Keys = make([]DCFKeyCompact, n)
		p1[j].Keys = make([]DCFKeyCompact, n)
		p0[j].MaskShare = make([]uint64, n)
		p1[j].MaskShare = make([]uint64, n)

		// Shift threshold to unsigned: threshold_shifted = (threshold + offset) mod mod
		threshShifted := (thresholds[j] + rp.SignThreshold) % mod

		for i := 0; i < n; i++ {
			// Random mask r in safe range
			r := cryptoRandUint64() % safeMax
			r0 := cryptoRandUint64() % mod
			r1 := (mod + r - r0) % mod

			// DCF alpha = (threshold_shifted + r) mod mod
			alpha := (threshShifted + r) % mod
			key0, key1 := DCFGen(alpha, 1, numBits)

			p0[j].Keys[i] = key0
			p1[j].Keys[i] = key1
			p0[j].MaskShare[i] = r0
			p1[j].MaskShare[i] = r1
		}
	}

	return p0, p1
}

// --- Round 1: Compute masked value ---

// CmpRound1Message is sent from one party to the peer.
type CmpRound1Message struct {
	MaskedValues [][]uint64 // [nCmp][n] masked eta values per comparison
}

// CmpRound1 computes party's round 1 message for all comparisons.
// etaShare is the party's share of eta (n elements in Ring63).
// preproc contains the party's DCF keys and mask shares.
// partyID: 0 or 1. Party 0 adds the sign offset (SignThreshold) to shift signed→unsigned.
func CmpRound1(rp RingParams, partyID int, etaShare []uint64, preproc []CmpPreprocessParty) CmpRound1Message {
	nCmp := len(preproc)
	n := len(etaShare)
	mod := rp.Modulus

	msg := CmpRound1Message{
		MaskedValues: make([][]uint64, nCmp),
	}

	for j := 0; j < nCmp; j++ {
		msg.MaskedValues[j] = make([]uint64, n)
		for i := 0; i < n; i++ {
			// Shift share to unsigned: party 0 adds offset, party 1 doesn't
			// (x0 + offset) + x1 = x + offset mod mod
			shifted := etaShare[i]
			if partyID == 0 {
				shifted = (etaShare[i] + rp.SignThreshold) % mod
			}
			// masked_i = shifted_share_i + mask_share_i (mod mod)
			msg.MaskedValues[j][i] = (shifted + preproc[j].MaskShare[i]) % mod
		}
	}

	return msg
}

// --- Round 2: Evaluate DCF → comparison bit shares ---

// CmpResult holds the comparison result shares for all comparisons.
type CmpResult struct {
	BitShares    [][]byte   // [nCmp][n] — additive mod-2 share (for AND gates)
	ArithShares  [][]uint64 // [nCmp][n] — arithmetic Ring63 share (for Beaver products)
}

// CmpRound2 evaluates DCF on the full masked value (own + peer) for all comparisons.
// Returns BOTH mod-2 bit shares AND Ring63 arithmetic shares.
// The arithmetic shares satisfy: share0 + share1 = 0 or 1 (mod Modulus).
func CmpRound2(partyID int, preproc []CmpPreprocessParty, ownR1 CmpRound1Message, peerR1 CmpRound1Message) CmpResult {
	nCmp := len(preproc)
	n := len(ownR1.MaskedValues[0])
	extBits := preproc[0].NumBits
	extMod := uint64(1) << extBits

	result := CmpResult{
		BitShares:   make([][]byte, nCmp),
		ArithShares: make([][]uint64, nCmp),
	}

	for j := 0; j < nCmp; j++ {
		result.BitShares[j] = make([]byte, n)
		result.ArithShares[j] = make([]uint64, n)
		for i := 0; i < n; i++ {
			m := (ownR1.MaskedValues[j][i] + peerR1.MaskedValues[j][i]) % extMod

			// DCFEval returns int64 share. Sum of two parties = 0 or 1.
			v := DCFEval(partyID, preproc[j].Keys[i], m)

			// Mod-2 bit share (for backward compat with AND gate tests)
			result.BitShares[j][i] = byte(((v % 2) + 2) % 2)

			// Ring63 arithmetic share: reduce int64 → uint64 mod Modulus
			// This preserves additivity: uint64(v0) + uint64(v1) ≡ 0 or 1 (mod 2^63)
			mod := uint64(1) << preproc[j].NumBits
			result.ArithShares[j][i] = uint64(v) % mod
		}
	}

	return result
}

// cryptoRandUint64 is in util.go
