args <- commandArgs(TRUE)
root <- normalizePath(args[[1]])
pkgload::load_all(file.path(root, "dsVert"), quiet = TRUE)
options(dsvert.mpc_binary = file.path(root, "dsVert/inst/bin/darwin-arm64/dsvert-mpc"))
env <- new.env(parent = asNamespace("dsVert"))
for (path in list.files(file.path(root, "dsVert/tests/testthat"), pattern = "^helper.*\\.R$", full.names = TRUE)) sys.source(path, env)
expressions <- parse(file.path(root, "dsVert/tests/testthat/test-crossgrid-cox.R"))
selected <- Filter(function(x) is.call(x) && (identical(x[[1L]], as.name("<-")) || (identical(x[[1L]], as.name("test_that")) && grepl("automatic context authenticates", x[[2L]], fixed = TRUE))), as.list(expressions))
path <- file.path(root, "dsVert/tests/testthat/cycle35-cache-selected.R")
writeLines(unlist(lapply(selected, deparse, width.cutoff = 500L)), path)
result <- testthat::test_file(path, env = env, reporter = "summary")
unlink(path)
frame <- as.data.frame(result)
stopifnot(all(frame$failed == 0), all(!frame$error), all(frame$warning == 0), all(frame$skipped == 0))
