args <- commandArgs(TRUE)
root <- normalizePath(args[[1]])
out <- normalizePath(args[[2]])
pkgload::load_all(file.path(root, "dsVert"), quiet = TRUE)
options(dsvert.mpc_binary = file.path(root, "dsVert/inst/bin/darwin-arm64/dsvert-mpc"))
env <- new.env(parent = asNamespace("dsVert"))
for (path in list.files(file.path(root, "dsVert/tests/testthat"), pattern = "^helper.*\\.R$", full.names = TRUE)) sys.source(path, env)
result <- testthat::test_file(file.path(root, "dsVert/tests/testthat/test-crossgrid-glmm-gaussian-preflight.R"), env = env, reporter = "summary")
frame <- as.data.frame(result)
write.csv(frame[setdiff(names(frame), "result")], file.path(out, "preflight-tests.csv"), row.names = FALSE)
stopifnot(all(frame$failed == 0), all(!frame$error), all(frame$warning == 0), all(frame$skipped == 0))
